#!/usr/bin/env python3
"""Guard — klc-plugin/ agents & command stubs stay in sync with source (KLC-092).

`phase_resolver.resolve_phase` dispatches each phase to the GENERATED copy under
`klc-plugin/agents/<stem>.md`, not to the `core/agents/` source. Those copies are
produced by `core/skills/plugin_gen.py`. If a `core/agents/*.md` prompt changes
but its plugin copy is not regenerated, the delivery layer silently serves a
stale (or missing) prompt to Claude Code plugin users. This guard turns that
drift into a red test instead of a silent delivery gap.

It covers two delivery artifacts in one file:
  * agents  — byte-exact compare. Regenerate every agent into a temp dir via
    `plugin_gen.generate_agents` and compare each output (frontmatter + body)
    against the committed `klc-plugin/agents/<name>.md`. Comparing the full
    generated bytes also catches model/frontmatter drift, not only body drift.
  * commands — presence check. Every verb `plugin_gen` emits (`_LIFECYCLE_CMDS`
    plus `run`) must have a committed `klc-plugin/commands/<verb>.md` stub. The
    stubs are static and the generator is skip-if-exists, so presence — not a
    byte compare — is the meaningful guarantee.

`core/skills/*.py` are out of scope (AC-5): they are imported from the framework
tree, not bundled into `klc-plugin/`. The guard asserts nothing about them and
verifies none is copied under `klc-plugin/`.
"""
from __future__ import annotations

import sys
import tempfile
from pathlib import Path

FW = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(FW / "core" / "skills"))
sys.path.insert(0, str(FW))

import plugin_gen as pg  # noqa: E402
import phases as _phases  # noqa: E402


def _agent_drift(committed_dir: Path) -> list[str]:
    """Regenerate all agents into a temp dir and return drift findings against
    *committed_dir*. An empty list means fully in sync.

    Each finding is ``MISSING: <name>`` (no committed copy) or
    ``DRIFT: <name>`` (committed copy differs from the regenerated bytes).
    """
    findings: list[str] = []
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / "agents"
        pg.generate_agents(output_dir=out)
        for gen in sorted(out.glob("*.md")):
            dst = committed_dir / gen.name
            if not dst.exists():
                findings.append(f"MISSING: {gen.name}")
            elif dst.read_bytes() != gen.read_bytes():
                findings.append(f"DRIFT: {gen.name}")
    return findings


def test_every_core_agent_has_in_sync_plugin_copy() -> None:
    """AC-1 / AC-2 / AC-4: every ``core/agents/*.md`` has a committed
    ``klc-plugin/agents/<name>.md`` copy whose bytes match what ``plugin_gen``
    regenerates from current source (this includes the reviewer agents)."""
    committed = FW / "klc-plugin" / "agents"
    drift = _agent_drift(committed)
    assert not drift, (
        "klc-plugin/agents/ is out of sync with core/agents/ — run "
        "`klc plugin-gen` and commit the regenerated files. Offending files:\n  "
        + "\n  ".join(drift)
    )


def test_guard_names_drifted_and_missing_files() -> None:
    """AC-4 negative arm: on a stale/missing tree the drift detector fails AND
    names the offending files, so a developer knows exactly what to regenerate.

    Builds a correct baseline in a temp dir, then corrupts one file and deletes
    another, and asserts both are reported by name.
    """
    with tempfile.TemporaryDirectory() as tmp:
        fake_committed = Path(tmp) / "committed"
        pg.generate_agents(output_dir=fake_committed)
        victims = sorted(fake_committed.glob("*.md"))
        assert len(victims) >= 2, "need >=2 generated agents to build the fixture"
        drifted, missing = victims[0], victims[1]
        drifted.write_text("stale body — not what plugin_gen emits\n", encoding="utf-8")
        missing.unlink()

        findings = _agent_drift(fake_committed)
        joined = "\n".join(findings)
        assert f"DRIFT: {drifted.name}" in joined, joined
        assert f"MISSING: {missing.name}" in joined, joined


def test_skills_out_of_scope() -> None:
    """AC-5: no ``core/skills/*.py`` is bundled under ``klc-plugin/`` (they are
    imported from the framework tree), and this guard makes no assertion about
    ``klc-plugin/skills`` content."""
    plugin = FW / "klc-plugin"
    skill_py_names = {p.name for p in (FW / "core" / "skills").glob("*.py")}
    copied = sorted(
        str(p.relative_to(FW))
        for p in plugin.rglob("*.py")
        if p.name in skill_py_names
    )
    assert not copied, (
        "core/skills/*.py must not be bundled into klc-plugin/ (they are imported "
        "from the framework tree). Found copies:\n  " + "\n  ".join(copied)
    )


def test_all_emitted_command_stubs_present() -> None:
    """AC-3: every command verb ``plugin_gen`` emits (``_LIFECYCLE_CMDS`` plus
    ``run``) has a committed ``klc-plugin/commands/<verb>.md`` stub. Presence —
    not a byte compare — is the guarantee, because the stubs are static and the
    generator skips existing files."""
    cmds = FW / "klc-plugin" / "commands"
    expected = list(pg._LIFECYCLE_CMDS) + ["run"]
    missing = [f"{verb}.md" for verb in expected if not (cmds / f"{verb}.md").exists()]
    assert not missing, (
        "klc-plugin/commands/ is missing stubs plugin_gen emits — run "
        "`klc plugin-gen` and commit the result. Missing:\n  " + "\n  ".join(missing)
    )


def test_phase_resolver_targets_committed_agent_copies() -> None:
    """Every prompt-bearing phase resolves to a committed plugin agent copy.

    `phase_resolver.resolve_phase` sets ``agent_type`` only when
    ``klc-plugin/agents/<prompt-stem>.md`` exists (see phase_resolver.py:65-70);
    a missing copy silently yields ``agent_type=None`` and disables the agent.
    This mirrors that existence gate for every phase whose prompt is set, so the
    regenerated delivery layer is proven to be exactly what the resolver reads."""
    committed = FW / "klc-plugin" / "agents"
    ph = _phases.load_phases()
    unresolved = []
    for phase in ph.ordered:
        if not phase.prompt:
            continue  # intake / integrate / observe have no dispatch agent
        stem = Path(phase.prompt).stem
        if not (committed / f"{stem}.md").exists():
            unresolved.append(f"{phase.id} -> {stem}.md")
    assert not unresolved, (
        "phase_resolver would return agent_type=None for these phases because "
        "their regenerated plugin agent copy is missing:\n  " + "\n  ".join(unresolved)
    )
