#!/usr/bin/env python3
"""Guard — klc-plugin/ agents & command stubs stay in sync with source (KLC-092).

`phase_resolver.resolve_phase` dispatches each phase to the GENERATED copy under
`klc-plugin/agents/<stem>.md`, not to the `core/agents/` source. Those copies are
produced by `core/skills/plugin_gen.py`. If a `core/agents/*.md` prompt changes
but its plugin copy is not regenerated, the delivery layer silently serves a
stale (or missing) prompt to Claude Code plugin users. This guard turns that
drift into a red test instead of a silent delivery gap.

It covers two delivery artifacts in one file:
  * agents  — byte-exact compare. Regenerate every agent into a temp dir via
    `plugin_gen.generate_agents` and compare each output (frontmatter + body)
    against the committed `klc-plugin/agents/<name>.md`. Comparing the full
    generated bytes also catches model/frontmatter drift, not only body drift.
  * commands — presence check. Every verb `plugin_gen` emits (`_LIFECYCLE_CMDS`
    only, KLC-180) must have a committed `klc-plugin/commands/<verb>.md` stub. The
    stubs are static and the generator is skip-if-exists, so presence — not a
    byte compare — is the meaningful guarantee.

`core/skills/*.py` are out of scope (AC-5): they are imported from the framework
tree, not bundled into `klc-plugin/`. The guard asserts nothing about them and
verifies none is copied under `klc-plugin/`.
"""
from __future__ import annotations

import sys
import tempfile
from pathlib import Path

FW = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(FW / "core" / "skills"))
sys.path.insert(0, str(FW))

import plugin_gen as pg  # noqa: E402
import phases as _phases  # noqa: E402

# KLC-102: the drift-guard now covers the WHOLE plugin, not only agents.
SKILLS_DIR = FW / "klc-plugin" / "skills"
MANIFEST_PATH = FW / "klc-plugin" / ".claude-plugin" / "plugin.json"
COMMANDS_DIR = FW / "klc-plugin" / "commands"


def _agent_drift(committed_dir: Path) -> list[str]:
    """Regenerate all agents into a temp dir and return drift findings against
    *committed_dir*. An empty list means fully in sync.

    Each finding is ``MISSING: <name>`` (no committed copy) or
    ``DRIFT: <name>`` (committed copy differs from the regenerated bytes).
    """
    findings: list[str] = []
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / "agents"
        pg.generate_agents(output_dir=out)
        for gen in sorted(out.glob("*.md")):
            dst = committed_dir / gen.name
            if not dst.exists():
                findings.append(f"MISSING: {gen.name}")
            elif dst.read_bytes() != gen.read_bytes():
                findings.append(f"DRIFT: {gen.name}")
    return findings


def test_every_core_agent_has_in_sync_plugin_copy() -> None:
    """AC-1 / AC-2 / AC-4: every agent ``plugin_gen`` ships (phase-owned prompts
    plus DISPATCHED_AGENTS) has a committed ``klc-plugin/agents/<name>.md`` copy
    whose bytes match what ``plugin_gen`` regenerates from current source."""
    committed = FW / "klc-plugin" / "agents"
    drift = _agent_drift(committed)
    assert not drift, (
        "klc-plugin/agents/ is out of sync with core/agents/ — run "
        "`klc plugin-gen` and commit the regenerated files. Offending files:\n  "
        + "\n  ".join(drift)
    )


def test_guard_names_drifted_and_missing_files() -> None:
    """AC-4 negative arm: on a stale/missing tree the drift detector fails AND
    names the offending files, so a developer knows exactly what to regenerate.

    Builds a correct baseline in a temp dir, then corrupts one file and deletes
    another, and asserts both are reported by name.
    """
    with tempfile.TemporaryDirectory() as tmp:
        fake_committed = Path(tmp) / "committed"
        pg.generate_agents(output_dir=fake_committed)
        victims = sorted(fake_committed.glob("*.md"))
        assert len(victims) >= 2, "need >=2 generated agents to build the fixture"
        drifted, missing = victims[0], victims[1]
        drifted.write_text("stale body — not what plugin_gen emits\n", encoding="utf-8")
        missing.unlink()

        findings = _agent_drift(fake_committed)
        joined = "\n".join(findings)
        assert f"DRIFT: {drifted.name}" in joined, joined
        assert f"MISSING: {missing.name}" in joined, joined


def test_skills_out_of_scope() -> None:
    """AC-5: no ``core/skills/*.py`` is bundled under ``klc-plugin/`` (they are
    imported from the framework tree), and this guard makes no assertion about
    ``klc-plugin/skills`` content."""
    plugin = FW / "klc-plugin"
    skill_py_names = {p.name for p in (FW / "core" / "skills").glob("*.py")}
    copied = sorted(
        str(p.relative_to(FW))
        for p in plugin.rglob("*.py")
        if p.name in skill_py_names
    )
    assert not copied, (
        "core/skills/*.py must not be bundled into klc-plugin/ (they are imported "
        "from the framework tree). Found copies:\n  " + "\n  ".join(copied)
    )


def test_all_emitted_command_stubs_present() -> None:
    """AC-3: every command verb ``plugin_gen`` emits (``_LIFECYCLE_CMDS``) has a committed ``klc-plugin/commands/<verb>.md`` stub. Presence —
    not a byte compare — is the guarantee, because the stubs are static and the
    generator skips existing files."""
    cmds = FW / "klc-plugin" / "commands"
    expected = list(pg._LIFECYCLE_CMDS)
    missing = [f"{verb}.md" for verb in expected if not (cmds / f"{verb}.md").exists()]
    assert not missing, (
        "klc-plugin/commands/ is missing stubs plugin_gen emits — run "
        "`klc plugin-gen` and commit the result. Missing:\n  " + "\n  ".join(missing)
    )


def test_phase_resolver_targets_committed_agent_copies() -> None:
    """Every prompt-bearing phase resolves to a committed plugin agent copy.

    `phase_resolver.resolve_phase` sets ``agent_type`` only when
    ``klc-plugin/agents/<prompt-stem>.md`` exists (see phase_resolver.py:65-70);
    a missing copy silently yields ``agent_type=None`` and disables the agent.
    This mirrors that existence gate for every phase whose prompt is set, so the
    regenerated delivery layer is proven to be exactly what the resolver reads."""
    committed = FW / "klc-plugin" / "agents"
    ph = _phases.load_phases()
    unresolved = []
    for phase in ph.ordered:
        if not phase.prompt:
            continue  # intake / integrate / observe have no dispatch agent
        stem = Path(phase.prompt).stem
        if not (committed / f"{stem}.md").exists():
            unresolved.append(f"{phase.id} -> {stem}.md")
    assert not unresolved, (
        "phase_resolver would return agent_type=None for these phases because "
        "their regenerated plugin agent copy is missing:\n  " + "\n  ".join(unresolved)
    )


# ===========================================================================
# KLC-102 — whole-plugin drift guard: skills byte-exact, manifest byte-exact,
# bespoke presence, skill-dir set-closure, and the command-desc byte-assert.
# ===========================================================================

def _skill_drift(committed_dir: Path) -> list[str]:
    """Regenerate the SKILL_VERBS skills into a temp dir and return drift
    findings against *committed_dir*. Empty list means fully in sync.

    Each finding is ``MISSING: <verb>/SKILL.md`` or ``DRIFT: <verb>/SKILL.md``.
    """
    findings: list[str] = []
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / "skills"
        pg.generate_skills(output_dir=out)
        for v in sorted(pg.SKILL_VERBS):
            gen = out / v / "SKILL.md"
            dst = committed_dir / v / "SKILL.md"
            if not dst.exists():
                findings.append(f"MISSING: {v}/SKILL.md")
            elif dst.read_bytes() != gen.read_bytes():
                findings.append(f"DRIFT: {v}/SKILL.md")
    return findings


def _manifest_drift(committed_manifest: Path) -> list[str]:
    """Regenerate the manifest into a temp dir and compare to
    *committed_manifest*. Empty list means in sync."""
    findings: list[str] = []
    with tempfile.TemporaryDirectory() as tmp:
        gen = pg.generate_manifest(output_dir=Path(tmp))
        if not committed_manifest.exists():
            findings.append("MISSING: .claude-plugin/plugin.json")
        elif committed_manifest.read_bytes() != gen.read_bytes():
            findings.append("DRIFT: .claude-plugin/plugin.json")
    return findings


def _skill_dir_findings(dir_names: set[str]) -> list[str]:
    """Set-closure check on an injectable set of skill-dir names: every dir must
    belong to ``SKILL_VERBS ∪ BESPOKE_SKILLS``. Returns ``UNKNOWN: <d>`` for an
    unguarded dir and ``MISSING: <d>`` for an expected dir that is absent."""
    known = pg.SKILL_VERBS | pg.BESPOKE_SKILLS
    return (
        [f"UNKNOWN: {d}" for d in sorted(dir_names - known)]
        + [f"MISSING: {d}" for d in sorted(known - dir_names)]
    )


def _committed_cmd_desc(md: Path) -> str:
    """The ``description:`` value from a committed command stub."""
    for line in md.read_text(encoding="utf-8").splitlines():
        if line.startswith("description:"):
            return line[len("description:"):].strip()
    raise AssertionError(f"no description: line in {md}")


def test_skills_in_sync() -> None:
    """AC-5: every SKILL_VERBS ``skills/<verb>/SKILL.md`` matches the bytes
    ``plugin_gen.generate_skills`` regenerates from source (extends KLC-092's
    agents-byte guarantee to the passthrough skills)."""
    drift = _skill_drift(SKILLS_DIR)
    assert not drift, (
        "klc-plugin/skills/ is out of sync — run "
        "`python3 core/skills/plugin_gen.py` and commit. Offending:\n  "
        + "\n  ".join(drift)
    )


def test_manifest_in_sync() -> None:
    """AC-5: the committed ``.claude-plugin/plugin.json`` matches the bytes
    ``generate_manifest`` emits."""
    drift = _manifest_drift(MANIFEST_PATH)
    assert not drift, (
        "klc-plugin/.claude-plugin/plugin.json is out of sync — run "
        "`python3 core/skills/plugin_gen.py` and commit. Offending:\n  "
        + "\n  ".join(drift)
    )


def test_bespoke_skills_present() -> None:
    """AC-6: each bespoke skill dir (discuss-feature) has a committed
    SKILL.md, AND every committed skill dir belongs to
    ``SKILL_VERBS ∪ BESPOKE_SKILLS`` (set-closure — no unguarded artifact,
    C-002)."""
    for b in pg.BESPOKE_SKILLS:
        assert (SKILLS_DIR / b / "SKILL.md").exists(), (
            f"bespoke skill {b}/SKILL.md is missing (presence-guarded)"
        )
    on_disk = {p.name for p in SKILLS_DIR.iterdir() if p.is_dir()}
    assert _skill_dir_findings(on_disk) == [], (
        "klc-plugin/skills/ set-closure violated (unknown or missing dir):\n  "
        + "\n  ".join(_skill_dir_findings(on_disk))
    )


def test_hand_edited_skill_is_red() -> None:
    """AC-6 negative arm: a hand-edited generated skill (byte diff) is reported
    as DRIFT, so C-003 is mechanically enforced."""
    with tempfile.TemporaryDirectory() as tmp:
        fake = Path(tmp) / "skills"
        pg.generate_skills(output_dir=fake)
        victim = sorted(pg.SKILL_VERBS)[0]
        (fake / victim / "SKILL.md").write_text(
            "hand-edited drift — not what plugin_gen emits\n", encoding="utf-8"
        )
        findings = _skill_drift(fake)
        assert any(f"DRIFT: {victim}/SKILL.md" in f for f in findings), findings


def test_deleted_bespoke_skill_is_red() -> None:
    """review F-1 / AC-6: a MISSING bespoke skill dir (discuss-feature removed)
    is reported, not silently passed."""
    on_disk = {p.name for p in SKILLS_DIR.iterdir() if p.is_dir()}
    on_disk.discard("discuss-feature")
    findings = _skill_dir_findings(on_disk)
    assert any("MISSING: discuss-feature" in f for f in findings), findings


def test_unknown_skill_dir_is_red() -> None:
    """review D-2 / C-002 / AC-6: a committed skill dir not in
    ``SKILL_VERBS ∪ BESPOKE_SKILLS`` fails the set-closure guard."""
    findings = _skill_dir_findings(pg.SKILL_VERBS | pg.BESPOKE_SKILLS | {"rogue"})
    assert any("UNKNOWN: rogue" in f for f in findings), findings


def test_command_desc_matches_verb_specs_short() -> None:
    """AC-4: for each shared verb, the committed ``commands/<verb>.md``
    ``description:`` equals ``VERB_SPECS[verb]["short"]`` — the single byte
    assertion that would have caught the live ``ack.md`` drift."""
    shared = pg.SKILL_VERBS & set(pg._LIFECYCLE_CMDS)
    for v in sorted(shared):
        md = COMMANDS_DIR / f"{v}.md"
        assert md.exists(), f"missing command stub {v}.md"
        assert _committed_cmd_desc(md) == pg.VERB_SPECS[v]["short"], (
            f"commands/{v}.md description drifts from VERB_SPECS[{v!r}]['short']"
        )
