"""KLC-178 step-5 — AC-12: help text, process doc, README and the plugin
describe one verb set (intake, status, go, back, fix, doctor; `step verify` is CLI-only), and no
teaching surface still presents the retired lifecycle commands as commands."""
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

FW = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(FW / "core" / "skills"))
import plugin_gen as pg  # noqa: E402

PLUGIN = FW / "klc-plugin"
PUBLIC = {"intake", "status", "go", "back", "fix", "doctor"}
RETIRED = ("retrack", "scope-fix", "install", "init", "update", "setup", "state init")


def _help() -> str:
    r = subprocess.run([sys.executable, str(FW / "scripts" / "klc"), "--help"],
                       capture_output=True, text=True, cwd=str(FW))
    return r.stdout + r.stderr


def test_help_docs_and_plugin_are_consistent():
    assert pg.check_sync() == []
    assert {"fix", "doctor"} <= pg.SKILL_VERBS
    assert {"fix", "doctor"} <= set(pg._LIFECYCLE_CMDS)
    for v in ("fix", "doctor"):
        assert (PLUGIN / "skills" / v / "SKILL.md").is_file()
        assert (PLUGIN / "commands" / f"{v}.md").is_file()
    cmds = {p.stem for p in (PLUGIN / "commands").glob("*.md")}
    assert PUBLIC <= cmds
    assert '"version": "0.2.0"' in (PLUGIN / ".claude-plugin" / "plugin.json").read_text("utf-8")

    h = _help()
    for v in ("fix", "doctor"):
        assert re.search(rf"\b{v}\b", h)
    assert "retrack" not in h and "scope-fix" not in h

    doc = (FW / "docs" / "process.md").read_text("utf-8")
    readme = (FW / "README.md").read_text("utf-8")
    for text in (doc, readme):
        assert "klc fix" in text and "klc doctor" in text
        assert "klc doctor --install" in text and "klc doctor --index" in text


def _teaching_files() -> list[Path]:
    files = [FW / "docs" / "process.md", FW / "README.md"]
    files += sorted((FW / "core" / "agents").rglob("*.md"))
    files += sorted((PLUGIN / "skills").rglob("*.md"))
    return files


def test_no_teaching_surface_presents_retired_commands():
    pat = re.compile(r"klc (retrack|scope-fix|install|init|update|setup|state init)\b")
    offenders = []
    for f in _teaching_files():
        for n, line in enumerate(f.read_text("utf-8").splitlines(), 1):
            if pat.search(line) and "deprecated" not in line.lower():
                offenders.append(f"{f.relative_to(FW)}:{n}: {line.strip()}")
    assert offenders == [], "\n".join(offenders)


def _frontmatter(path: Path) -> dict[str, str]:
    lines = path.read_text("utf-8").splitlines()
    assert lines[0] == "---"
    end = lines.index("---", 1)
    return dict(l.split(": ", 1) for l in lines[1:end] if ": " in l)


def test_fix_and_doctor_skills_are_operator_only_and_doctor_hint_is_honest():
    """F-003/F-005: a model must not retrack a ticket or run --install on its own."""
    for v in ("fix", "doctor"):
        fm = _frontmatter(PLUGIN / "skills" / v / "SKILL.md")
        assert fm.get("disable-model-invocation") == "true", v
    for v in sorted(pg.SKILL_VERBS - {"fix", "doctor"}):
        assert "disable-model-invocation" not in _frontmatter(PLUGIN / "skills" / v / "SKILL.md")
    for f in (PLUGIN / "skills" / "doctor" / "SKILL.md", PLUGIN / "commands" / "doctor.md"):
        assert _frontmatter(f)["argument-hint"] == "[--install <root>] [--index]"
    skill = (PLUGIN / "skills" / "doctor" / "SKILL.md").read_text("utf-8")
    assert "ticket" not in skill.lower() and "TICKET" not in skill


def test_readme_setup_sample_matches_what_doctor_prints():
    readme = (FW / "README.md").read_text("utf-8")
    assert "[setup]" not in readme
    assert "languages:" in readme


_EXACT_ONLY = {"core/skills/index_health.py"}  # allowlist must equal the literal, not just occur in it

_ALLOWED_LITERALS = (
    # (file, substring, reason)
    ("core/skills/hook_install.py", "generated by `klc install`", "load-bearing hook marker"),
    ("core/skills/hook_install.py", "BEGIN klc install", "load-bearing hook marker"),
    ("core/skills/hook_install.py", "END klc install", "load-bearing hook marker"),
    # EXACT match only: the literal passed to render_snippet as the hook command.
    ("core/skills/index_health.py", "klc update", "hook snippet command the hook pins; KLC-180"),
    ("core/phases/state.py", "klc state init", "deprecated module's own usage"),
)


def test_core_string_literals_do_not_teach_retired_commands():
    """F-006: the guard covers code messages, not only docs."""
    import ast
    pat = re.compile(r"klc (retrack|scope-fix|install|init|update|setup|state init)\b(?!:)")
    offenders = []
    files = (sorted((FW / "core" / "skills").glob("*.py")) + sorted((FW / "core" / "phases").glob("*.py"))
             + sorted((FW / "scripts").glob("*.py")))
    for f in files:
        rel = str(f.relative_to(FW))
        tree = ast.parse(f.read_text("utf-8"))
        skip = set()
        for n in ast.walk(tree):
            if isinstance(n, (ast.Module, ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)) \
                    and n.body and isinstance(n.body[0], ast.Expr) \
                    and isinstance(n.body[0].value, ast.Constant):
                skip.add(id(n.body[0].value))
            if isinstance(n, ast.Call):
                skip.update(id(k.value) for k in n.keywords if k.arg == "prog")
        for n in ast.walk(tree):
            if not (isinstance(n, ast.Constant) and isinstance(n.value, str)) or id(n) in skip:
                continue
            if not pat.search(n.value) or "deprecated" in n.value.lower():
                continue
            if any(rel == a and (n.value == sub or (sub in n.value and rel not in _EXACT_ONLY))
                   for a, sub, _ in _ALLOWED_LITERALS):
                continue
            offenders.append(f"{rel}:{n.lineno}: {n.value.strip()[:80]!r}")
    assert offenders == [], "\n".join(offenders)
