"""KLC-103 — AC-5: exactly one documented on-disk inventory schema.

The canonical shape is stated once, in `core/shared/inventory.py`
(`CANONICAL_SCHEMA` / `SYMBOL_FIELDS`). This file asserts that every producer
and every prompt that claims to write or read `.klc/index/inventory.json`
agrees with that one statement — not a second, independently maintained copy.
"""
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
SKILLS = REPO_ROOT / "core" / "skills"
sys.path.insert(0, str(SKILLS))

import deterministic_inventory as di  # noqa: E402

from core.shared.inventory import SYMBOL_FIELDS  # noqa: E402


def _fixture(tmp_path: Path) -> Path:
    root = tmp_path / "proj"
    (root / "pkg").mkdir(parents=True)
    (root / "pkg" / "mod.py").write_text(
        "def public_fn(a, b):\n"
        "    return a + b\n\n"
        "class PublicThing:\n"
        "    pass\n",
        encoding="utf-8",
    )
    return root


def test_deterministic_builder_output_matches_documented_schema(tmp_path):
    """AC-5 / AC-12: the deterministic builder's output field set is exactly the
    one `core.shared.inventory.SYMBOL_FIELDS` documents — one statement, one
    producer, verified against real output (not a fixture)."""
    root = _fixture(tmp_path)
    ruleset = di.resolve_ruleset()
    inv = di.build_inventory(root, ruleset, None)  # regex path — no ast-grep dependency
    assert inv["symbols"], "fixture must yield at least one symbol"
    for s in inv["symbols"]:
        assert set(s) == set(SYMBOL_FIELDS)
    assert set(inv) == {"root", "profile", "source_of_truth", "symbols", "errors", "notes"}


def test_regex_fallback_still_yields_flat_schema(tmp_path):
    """Edge case (test-plan.md): ast-grep missing/unavailable → regex fallback
    still yields the flat canonical shape, not a degraded/partial one."""
    root = _fixture(tmp_path)
    ruleset = di.resolve_ruleset()
    inv = di.build_inventory(root, ruleset, None)
    assert isinstance(inv["symbols"], list)
    assert any("regex" in e.lower() for e in inv["errors"])
    for s in inv["symbols"]:
        assert s["source_of_truth"] == "regex"
        assert set(s) == set(SYMBOL_FIELDS)


def _load_module_writer():
    import importlib.util
    spec = importlib.util.spec_from_file_location("klc103_module_writer_2",
                                                    str(SKILLS / "module-writer.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_inventory_hash_baseline_regenerated_for_new_schema(tmp_path, monkeypatch):
    """C-006: `_inventory_hash_payload()`'s `total_symbols` is now an int (the
    symbol COUNT via the shared accessor), not the raw (retired mapping-shaped)
    `symbols` collection. .klc/index/ is git-ignored (F-105), so the baseline
    is regenerated by re-running module-writer, not by committing a file — this
    test asserts the payload SHAPE the regeneration produces."""
    monkeypatch.setenv("PROJECT_ROOT", str(tmp_path))
    idx = tmp_path / ".klc" / "index"
    idx.mkdir(parents=True)
    (idx / "inventory.json").write_text(json.dumps({
        "symbols": [
            {"name": "f", "kind": "function", "file": "a.py", "line": 1,
             "signature": "", "visibility": "public", "source_of_truth": "ast_grep",
             "lang": "python", "rule": "r"},
        ],
        "notes": [],
    }), encoding="utf-8")
    (idx / "modules.json").write_text(json.dumps({"modules": [], "cycles": [],
                                                   "notes": []}), encoding="utf-8")
    mw = _load_module_writer()
    payload = mw._inventory_hash_payload()
    assert payload["total_symbols"] == 1
    assert isinstance(payload["total_symbols"], int)


def test_inventory_agent_prompt_states_canonical_schema():
    """AC-5: the inventory LLM agent prompt (core/agents/inventory.md) states
    the SAME schema as core.shared.inventory.CANONICAL_SCHEMA — one statement,
    not a second, independently maintained copy — and must not claim to write
    inventory.json itself (D-103: it writes inventory-annotations.json)."""
    from core.shared.inventory import SYMBOL_FIELDS

    text = (REPO_ROOT / "core" / "agents" / "inventory.md").read_text(encoding="utf-8")
    for field in SYMBOL_FIELDS:
        assert f'"{field}"' in text, f"inventory.md schema is missing field {field!r}"
    # The retired per-language mapping / embedded structural+depgraph shape must
    # not be restated as the on-disk contract any more.
    assert '"structural":' not in text
    assert '"depgraph":' not in text
    assert "inventory-annotations.json" in text
    assert "ONLY writer" in text or "only writer" in text.lower()


def test_no_producer_writes_an_alternate_inventory_shape():
    """AC-5: static scan of the known CANDIDATE producers of
    `.klc/index/inventory.json` (the deterministic builder, the inventory
    agent prompt + its deployed plugin copy, and the init/update scripts
    that orchestrate them) for any emitted/claimed key set that is not the
    flat schema. A file that merely READS inventory.json (e.g. a consumer
    skill's `--in-inventory` argument, or a wholly unrelated artifact that
    happens to share a key name like `symbol_usage.py`'s own
    `"symbols": {...}` output schema) is deliberately out of scope — this
    guards PRODUCERS, which is what AC-5 requires ('no producer ... writes
    any other shape')."""
    forbidden_markers = ('"symbols": {', '"items":', '"structural":      {',
                         '"depgraph":        {')
    candidate_producers = [
        REPO_ROOT / "core" / "agents" / "inventory.md",
        REPO_ROOT / "klc-plugin" / "agents" / "inventory.md",
        REPO_ROOT / "scripts" / "init.py",
        REPO_ROOT / "scripts" / "update.py",
    ]
    offenders = []
    for p in candidate_producers:
        if not p.exists():
            continue
        text = p.read_text(encoding="utf-8", errors="ignore")
        for marker in forbidden_markers:
            if marker in text:
                offenders.append((str(p.relative_to(REPO_ROOT)), marker))
    assert not offenders, f"alternate inventory.json shape(s) found: {offenders}"
