#!/usr/bin/env python3
"""baseline_compare.py — render and record the KLC-149 three-column baseline
comparison (published 2026-09-25 / old ground truth today / corrected ground
truth today) for `docs/20260920_klc110-retrieval-baseline.md`.

It loads `planning-eval.py` only via `retrieval_eval.load_planning_eval()`
(D-213), never a second `exec_module()` of its own, so `population_summary`
and `rank_metrics` stay the ONE implementation across every caller.

CLI (step-4):
    baseline_compare.py record --label {old,corrected} --code-dir D
        --code-commit SHA --work-dir W --out O -- BACKFILL_ARGS
    baseline_compare.py render --published P --published-source SPEC
        --old O --corrected C --doc D
"""
from __future__ import annotations

import argparse
import ast
import hashlib
import json
import re
import shlex
import subprocess
import sys
from pathlib import Path

_SKILLS_DIR = Path(__file__).resolve().parent
if str(_SKILLS_DIR) not in sys.path:
    sys.path.insert(0, str(_SKILLS_DIR))
import retrieval_eval as _reval  # noqa: E402  (D-213: the one planning-eval loader)

_pe = _reval.load_planning_eval()

BEGIN_MARK = "<!-- BEGIN: generated by core/skills/baseline_compare.py render; do not hand-edit -->"
END_MARK = "<!-- END: generated by core/skills/baseline_compare.py render -->"

_FIELDS = (
    ("tickets total", "total"),
    ("tickets scored", "scored"),
    ("tickets unavailable", "unavailable"),
    ("precision@5 mean", "precision_at_5_mean"),
    ("recall@10 mean", "recall_at_10_mean"),
)


def git_blob_id(data: bytes) -> str:
    """The git blob object id of *data* (KLC-149 D-204: pins the published
    snapshot to the exact historical blob, not to a working-tree copy)."""
    return hashlib.sha1(b"blob %d\0" % len(data) + data).hexdigest()


# --------------------------------------------------------------------------- #
# parsing a render_backfill-shaped text (step-3, AC-9)
# --------------------------------------------------------------------------- #
def _match_bullet(text: str, label: str) -> str | None:
    pattern = re.compile(rf"^- {re.escape(label)}: (.+)$", re.MULTILINE)
    m = pattern.search(text)
    return m.group(1).strip() if m else None


def _parse_value(raw: str):
    if raw == "null":
        return None
    try:
        return int(raw)
    except ValueError:
        pass
    try:
        return float(raw)
    except ValueError:
        return raw


def parse_backfill_md(text: str) -> dict:
    """Parse a `render_backfill`-shaped text (or the 'rendered table'
    section of the published baseline doc) into `{'measured',
    'index_generation', 'populations': {source: {five figures}}}`. Fails
    closed (`ValueError`) on a missing header bullet or a missing
    per-population bullet (KLC-149 AC-9)."""
    measured = _match_bullet(text, "measured")
    if measured is None:
        raise ValueError("backfill text is missing the '- measured:' bullet")
    index_generation = _match_bullet(text, "index generation")
    if index_generation is None:
        raise ValueError("backfill text is missing the '- index generation:' bullet")

    populations: dict[str, dict] = {}
    for source in ("stored", "replayed"):
        heading = f"## {source}\n"
        if heading not in text:
            continue
        section = text.split(heading, 1)[1]
        end = section.find("\n## ")
        block = section if end == -1 else section[:end]
        fields: dict = {}
        for label, key in _FIELDS:
            val = _match_bullet(block, label)
            if val is None:
                raise ValueError(
                    f"backfill text's '## {source}' section is missing the "
                    f"'- {label}:' bullet")
            fields[key] = _parse_value(val)
        populations[source] = fields

    return {"measured": measured, "index_generation": index_generation,
           "populations": populations}


# --------------------------------------------------------------------------- #
# the comparison renderer (step-3, AC-8/AC-9/AC-10)
# --------------------------------------------------------------------------- #
def _fmt(value):
    return "null" if value is None else value


def _keys(run: dict) -> set:
    return {(r["ticket"], r["trace_source"])
           for rows in run["rows"].values() for r in rows}


def per_ticket_rows(old: dict, corrected: dict) -> list[dict]:
    """AC-10: one row per `(ticket, trace_source)`, old and corrected
    status/derivation_source/precision@5/recall@10 next to each other, with
    a `changed` flag set when the status OR the derivation_source differs
    between the two runs. Iterates in a fixed order — sources `stored` then
    `replayed`, tickets in the old run's row order — never a clock, never a
    dict-ordering accident (`render_comparison` has already refused a
    differing ticket set, so every old row has a corresponding corrected
    one)."""
    corrected_by_key = {(r["ticket"], r["trace_source"]): r
                        for rows in corrected["rows"].values() for r in rows}
    out = []
    for source in ("stored", "replayed"):
        for o in old["rows"].get(source) or []:
            key = (o["ticket"], o["trace_source"])
            c = corrected_by_key[key]
            changed = (o.get("status") != c.get("status")
                      or o.get("derivation_source") != c.get("derivation_source"))
            out.append({
                "ticket": o["ticket"], "trace_source": o["trace_source"],
                "old_status": o.get("status"), "corrected_status": c.get("status"),
                "old_derivation_source": o.get("derivation_source"),
                "corrected_derivation_source": c.get("derivation_source"),
                "old_precision_at_5": o.get("precision_at_5"),
                "old_recall_at_10": o.get("recall_at_10"),
                "corrected_precision_at_5": c.get("precision_at_5"),
                "corrected_recall_at_10": c.get("recall_at_10"),
                "changed": changed,
            })
    return out


def _per_ticket_table(old: dict, corrected: dict) -> list[str]:
    rows = per_ticket_rows(old, corrected)
    lines = [
        "### per-ticket", "",
        "| ticket | trace_source | old status | corrected status | "
        "old derivation_source | corrected derivation_source | "
        "old precision@5 | old recall@10 | corrected precision@5 | "
        "corrected recall@10 | changed |",
        "|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| {r['ticket']} | {r['trace_source']} | {r['old_status']} | "
            f"{r['corrected_status']} | {r['old_derivation_source']} | "
            f"{r['corrected_derivation_source']} | {_fmt(r['old_precision_at_5'])} | "
            f"{_fmt(r['old_recall_at_10'])} | {_fmt(r['corrected_precision_at_5'])} | "
            f"{_fmt(r['corrected_recall_at_10'])} | {r['changed']} |")
    lines.append("")
    return lines


_COLUMNS = (("published", "published 2026-09-25"),
           ("old", "old ground truth, today"),
           ("corrected", "corrected ground truth, today"))


def _header(pub: dict, published_source: str, old: dict, corrected: dict,
           summaries: dict) -> list[str]:
    """external review F-4: besides the old/corrected measured times and
    commands, the header also carries the PUBLISHED column's own measured
    time and index generation (parsed from the snapshot by `pub`, not
    silently dropped) and one availability line per rendered population per
    column (`published`/`old`/`corrected`) — `scored`/`total` from the same
    `population_summary` the body table uses, so the doc intro's claim that
    the header lists 'availability per population' is true of the bytes."""
    corpus = len(_keys(old))
    lines = [
        f"- published column source: {published_source}",
        f"- published measured: {pub.get('measured', 'n/a')}",
        f"- published index generation: {pub.get('index_generation', 'n/a')}",
        f"- old ground truth measured: {old.get('measured', 'n/a')} "
        f"(code {old.get('code_commit', 'n/a')})",
        f"- old ground truth command: {old.get('command', 'n/a')}",
        f"- corrected ground truth measured: {corrected.get('measured', 'n/a')} "
        f"(code {corrected.get('code_commit', 'n/a')})",
        f"- corrected ground truth command: {corrected.get('command', 'n/a')}",
        f"- index generation (old and corrected): {old['index_generation']}",
        f"- corpus (ticket, trace_source) pairs: {corpus}",
    ]
    for source in ("stored", "replayed"):
        if source not in summaries:
            continue
        for col_key, col_label in _COLUMNS:
            avail = summaries[source][col_key]
            lines.append(
                f"- {source} availability ({col_label}): "
                f"{_fmt(avail['scored'])}/{_fmt(avail['total'])} scored")
    lines.append("")
    return lines


def render_comparison(published_text: str, published_source: str,
                      old: dict, corrected: dict) -> str:
    """Render the one generated block: the header, a three-column summary
    table per population, and the per-ticket comparison table. Fails closed
    (never half-renders): different index generations or different scored
    ticket sets between *old* and *corrected* raise `ValueError` (A-001)."""
    if old["index_generation"] != corrected["index_generation"]:
        raise ValueError(
            "old and corrected runs used different index generations (A-001)")
    if _keys(old) != _keys(corrected):
        raise ValueError(
            "old and corrected runs scored different ticket sets (A-001)")

    pub = parse_backfill_md(published_text)
    empty_pub = {"total": "n/a", "scored": "n/a", "unavailable": "n/a",
                "precision_at_5_mean": "n/a", "recall_at_10_mean": "n/a"}

    summaries: dict = {}
    for source in ("stored", "replayed"):
        o_rows = old["rows"].get(source) or []
        c_rows = corrected["rows"].get(source) or []
        if not o_rows and not c_rows and source not in pub["populations"]:
            continue
        summaries[source] = {
            "published": pub["populations"].get(source, empty_pub),
            "old": _pe.population_summary(o_rows),
            "corrected": _pe.population_summary(c_rows),
        }

    lines = [BEGIN_MARK, ""] + _header(pub, published_source, old, corrected, summaries)
    for source, s in summaries.items():
        lines += [
            f"### {source}", "",
            "| metric | published 2026-09-25 | old ground truth, today | "
            "corrected ground truth, today |",
            "|---|---|---|---|",
        ]
        lines += [f"| {label} | {_fmt(s['published'][key])} | {_fmt(s['old'][key])} | "
                 f"{_fmt(s['corrected'][key])} |" for label, key in _FIELDS]
        lines.append("")
    lines += _per_ticket_table(old, corrected) + [END_MARK]
    return "\n".join(lines) + "\n"


def splice_generated(doc_text: str, block: str) -> str:
    """Replace the single `BEGIN_MARK`..`END_MARK` span in *doc_text* with
    *block* (which must itself carry the same markers). Fails closed on a
    missing or a duplicated marker pair — never guesses which span to
    replace.

    Whatever run of `"\n"` characters (LF only — a lone `"\r"` left over
    from a CRLF doc is not part of this run and is left in place,
    immediately after the newly spliced block) follows the OLD `END_MARK`
    is consumed and discarded, and exactly ONE blank line is written in its
    place: *block* already ends in its own trailing newline
    (`render_comparison`'s `"\n".join(lines) + "\n"`), and this function
    appends exactly one more `"\n"` on top of that — never *block*'s
    newline plus the doc's own leftover run, and never zero extra newlines
    either, so a blank line is inserted even when the OLD `END_MARK` was
    followed immediately by text with no newline at all. The result is the
    same normalised shape regardless of how many newlines (zero, one, or
    many) the input had, which is what makes a second splice of the SAME
    block a byte no-op (idempotent), and makes re-splicing into an
    ALREADY-doubled doc collapse it back to a single trailing blank line
    (KLC-149 external review F-2: the old code kept `doc_text[end:]`
    verbatim — no consumption at all — so each re-splice appended one more
    blank line forever)."""
    begins = doc_text.count(BEGIN_MARK)
    ends = doc_text.count(END_MARK)
    if begins == 0 or ends == 0:
        raise ValueError("doc has no BEGIN_MARK/END_MARK pair to splice into")
    if begins > 1 or ends > 1:
        raise ValueError("doc has more than one BEGIN_MARK/END_MARK pair")
    start = doc_text.index(BEGIN_MARK)
    end = doc_text.index(END_MARK) + len(END_MARK)
    rest = end
    while doc_text[rest:rest + 1] == "\n":
        rest += 1
    return doc_text[:start] + block + "\n" + doc_text[rest:]


# --------------------------------------------------------------------------- #
# recording a "today" run from a given code tree (step-4, AC-9/AC-12/AC-14)
# --------------------------------------------------------------------------- #
class RecordError(RuntimeError):
    """A run that must not be recorded; nothing is written."""


def _code_dir_core_tree(code_dir: Path) -> dict[str, str]:
    """path (POSIX, relative to *code_dir*, under `core/`) -> git blob id,
    for every FILE under *code_dir*/core (external review F-3: widened from
    the single hardcoded `core/skills/planning-eval.py` to the whole
    `core/` subtree — any OTHER loaded file, `core/phases/state.py`,
    `retrieval_eval.py`, was unchecked before). `__pycache__` directories
    and `.pyc`/`.pyo` files are skipped: they are interpreter-written build
    artifacts that `git ls-tree` never reports either, and comparing them
    would make this check flaky (importing a module mid-run can create one
    on the *code_dir* side with no counterpart at the commit). Raises
    `RecordError` when *code_dir* has no `core/` directory at all —
    refusing to compare a tree it cannot even walk. Also raises
    `RecordError`, naming the path, on a SYMLINK anywhere under `core/`
    (review round 3 external F-3): `Path.is_file()` follows a symlink
    through to its target, so the old code would silently hash whatever the
    link resolves to — a file that may live outside `core/` entirely, may
    not exist at *code_commit* in the repo at all, or may rot after the
    record is made. Refusing is the only honest response; this function
    never follows one."""
    base = code_dir / "core"
    if not base.is_dir():
        raise RecordError(
            f"{code_dir} has no core/ directory; refusing to verify "
            f"--code-commit against it (KLC-149 external review F-3)")
    out: dict[str, str] = {}
    for p in sorted(base.rglob("*")):
        if "__pycache__" in p.parts:
            continue
        if p.is_symlink():
            raise RecordError(
                f"{p} is a symlink under {code_dir}/core; refusing to follow "
                f"it (KLC-149 review round 3 external F-3)")
        if not p.is_file() or p.suffix in (".pyc", ".pyo"):
            continue
        out[p.relative_to(code_dir).as_posix()] = git_blob_id(p.read_bytes())
    return out


def _repo_core_tree(repo: Path, code_commit: str) -> dict[str, str] | None:
    """path (POSIX, relative, under `core/`) -> blob id, from
    `git ls-tree -r -z <code_commit> -- core/` inside *repo*. `None` when
    *code_commit* does not resolve to a commit in *repo* at all (external
    review F-3: the caller reports THAT refusal with its own message,
    distinct from "resolves fine but a blob differs"). `-z` (review round 3
    external F-3) NUL-terminates each record instead of the default LF and,
    just as importantly, turns OFF git's default path quoting
    (`core.quotePath`): without it, a non-ASCII `core/` filename comes back
    C-quoted in octal escapes (e.g. `"caf\\303\\251.py"`), which never
    equals `_code_dir_core_tree`'s raw, un-quoted
    `Path.relative_to(...).as_posix()` string for the SAME file — the two
    sides would report a real, byte-identical file as present on only one
    side."""
    probe = subprocess.run(
        ["git", "rev-parse", "--verify", "--quiet", f"{code_commit}^{{commit}}"],
        capture_output=True, text=True, cwd=str(repo))
    if probe.returncode != 0:
        return None
    proc = subprocess.run(
        ["git", "ls-tree", "-r", "-z", code_commit, "--", "core/"],
        capture_output=True, text=True, cwd=str(repo))
    if proc.returncode != 0:
        return {}
    out: dict[str, str] = {}
    for record in proc.stdout.split("\0"):
        if not record.strip():
            continue
        meta, path = record.split("\t", 1)
        out[path] = meta.split()[2]
    return out


def _code_commit_mismatch(code_dir: Path, code_commit: str, repo: Path) -> str | None:
    """`None` iff every file under *code_dir*/core has the SAME git blob id
    as the same path under `core/` at *code_commit* in *repo* — a byte-exact,
    file-by-file comparison of the WHOLE `core/` subtree (external review
    F-3: widened from `core/skills/planning-eval.py` alone; a path present
    on only one side is also a mismatch). Otherwise one line per problem,
    so the caller's `RecordError` carries two clearly separate refusal
    shapes: *code_commit* not resolving to a commit at all in *repo*, versus
    resolving fine but disagreeing file by file (both blob ids shown)."""
    repo_tree = _repo_core_tree(repo, code_commit)
    if repo_tree is None:
        return (f"{code_commit!r} does not resolve to a commit in {repo} "
                f"(KLC-149 external review F-3)")
    code_tree = _code_dir_core_tree(code_dir)
    problems = []
    for path in sorted(set(code_tree) | set(repo_tree)):
        in_code, in_repo = path in code_tree, path in repo_tree
        if in_code and not in_repo:
            problems.append(f"{path}: present in {code_dir} but not in {code_commit}:core/")
        elif in_repo and not in_code:
            problems.append(f"{path}: present in {code_commit}:core/ but not in {code_dir}")
        elif code_tree[path] != repo_tree[path]:
            problems.append(
                f"{path}: blob {code_tree[path]} in {code_dir} != "
                f"blob {repo_tree[path]} in {code_commit}:core/")
    return "; ".join(problems) if problems else None


def _repo_from_backfill_args(backfill_args: list[str]) -> Path | None:
    """The `--repo` value out of *backfill_args*, in either `--repo PATH` or
    `--repo=PATH` form (external review F-3: the old code recognised only
    the separate-token form, so `--repo=PATH` silently acted as if no
    `--repo` were given at all — and `_portable`'s REPO_ROOT substitution
    silently skipped too). `None` when neither form is present anywhere. A
    trailing, valueless `--repo` (no token after it) raises `RecordError`
    instead of letting an `IndexError` escape."""
    for i, arg in enumerate(backfill_args):
        if arg == "--repo":
            if i + 1 >= len(backfill_args):
                raise RecordError(
                    "backfill_args ends with a bare --repo and no value "
                    "(KLC-149 external review F-3)")
            return Path(backfill_args[i + 1])
        if arg.startswith("--repo="):
            return Path(arg[len("--repo="):])
    return None


def _git_touched_has_all(code_dir: Path) -> bool:
    """True iff *code_dir*'s `git_touched` still holds the constant `--all`
    probe (an AST scan, not a text grep, so a `--all` appearing only in a
    comment or docstring elsewhere in the file can never flip the label
    check). Raises `RecordError` when the tree holds no `git_touched` at
    all — refusing to label a tree it cannot even inspect — and the SAME
    when *code_dir* has no `core/skills/planning-eval.py` file at all
    (external review F-3: a bare `FileNotFoundError` used to escape here
    instead of the one documented failure mode)."""
    script = code_dir / "core" / "skills" / "planning-eval.py"
    if not script.is_file():
        raise RecordError(
            f"{script} does not exist; refusing to label {code_dir} "
            f"(KLC-149 external review F-3)")
    src = script.read_text(encoding="utf-8")
    tree = ast.parse(src)
    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef) and node.name == "git_touched":
            return any(isinstance(n, ast.Constant) and n.value == "--all"
                      for n in ast.walk(node))
    raise RecordError(f"no git_touched function found in {script}; refusing to label it")


def _portable(argv: list[str], code_dir: Path, work_dir: Path,
              backfill_args: list[str]) -> str:
    """The executed argv with machine-local roots replaced mechanically
    (review decision D-1: the doc is mirrored publicly): `sys.executable` ->
    `python3`, *code_dir* -> `CODE_DIR`, *work_dir* -> `WORK_DIR`, the
    `--repo` value -> `REPO_ROOT`. The raw argv goes to the build log only,
    never into a committed file."""
    repo = _repo_from_backfill_args(backfill_args)
    subs = [(str(code_dir), "CODE_DIR"), (str(work_dir), "WORK_DIR")]
    if repo:
        subs.append((str(repo), "REPO_ROOT"))
    out = ["python3"] + list(argv[1:])
    for old, new in sorted(subs, key=lambda kv: -len(kv[0])):
        out = [a.replace(old, new) for a in out]
    return shlex.join(out)


def record_run(label: str, code_dir: Path, code_commit: str,
              backfill_args: list[str], work_dir: Path, out: Path) -> dict:
    """Run *code_dir*'s `planning-eval.py --backfill` with *backfill_args*
    inside *work_dir*, and write one JSON record (`label`, `code_commit`,
    the portable `command`, `measured`, `index_generation`, `rows`) to
    *out*. Refuses (`RecordError`, nothing written) a tree whose
    `git_touched` does not match *label* — `'old'` must still hold the
    `--all` probe, `'corrected'` must not (operator ruling D-2) — refuses a
    *code_commit* whose `core/` tree in `--repo`, FILE BY FILE (every file
    under `core/`, not just `core/skills/planning-eval.py`), does not match
    *code_dir*'s own `core/` tree, blob for blob (external review F-1: the
    operator-typed commit is machine-checked, not taken on faith; external
    review F-3: widened from the one file to the whole subtree), and fails
    closed when the backfill itself exits non-zero."""
    has_all = _git_touched_has_all(code_dir)
    if has_all != (label == "old"):
        raise RecordError(
            f"{code_dir} does not match label {label!r} "
            f"(git_touched holds '--all': {has_all}) — KLC-149 D-206")

    repo = _repo_from_backfill_args(backfill_args)
    if repo is None:
        raise RecordError(
            f"backfill_args carries no --repo; cannot verify code_commit "
            f"{code_commit!r} against {code_dir} (KLC-149 external review F-1)")
    mismatch = _code_commit_mismatch(code_dir, code_commit, repo)
    if mismatch is not None:
        raise RecordError(
            f"--code-commit {code_commit!r} does not match --code-dir {code_dir} "
            f"(KLC-149 external review F-1/F-3): {mismatch}")

    work_dir.mkdir(parents=True, exist_ok=True)
    run_json = work_dir / f"{label}.json"
    run_md = work_dir / f"{label}.md"
    argv = [sys.executable, str(code_dir / "core" / "skills" / "planning-eval.py"),
           "--backfill", "--trace-source", "both", *backfill_args,
           "--out", str(run_json), "--out-md", str(run_md)]
    proc = subprocess.run(argv, capture_output=True, text=True)
    if proc.returncode != 0:
        raise RecordError(
            f"backfill failed for label {label!r} (exit {proc.returncode}): "
            f"{proc.stderr.strip()[-2000:]}")

    head = parse_backfill_md(run_md.read_text(encoding="utf-8"))
    record = {
        "label": label,
        "code_commit": code_commit,
        "command": _portable(argv, code_dir, work_dir, backfill_args),
        "measured": head["measured"],
        "index_generation": head["index_generation"],
        "rows": json.loads(run_json.read_text(encoding="utf-8"))["rows"],
    }
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(record, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return record


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #
def _main_record(argv: list[str]) -> int:
    if "--" in argv:
        idx = argv.index("--")
        own_argv, backfill_args = argv[:idx], argv[idx + 1:]
    else:
        own_argv, backfill_args = argv, []
    ap = argparse.ArgumentParser(prog="baseline_compare.py record")
    ap.add_argument("--label", choices=("old", "corrected"), required=True)
    ap.add_argument("--code-dir", type=Path, required=True)
    ap.add_argument("--code-commit", required=True)
    ap.add_argument("--work-dir", type=Path, required=True)
    ap.add_argument("--out", type=Path, required=True)
    args = ap.parse_args(own_argv)
    try:
        record_run(args.label, args.code_dir, args.code_commit, backfill_args,
                  args.work_dir, args.out)
    except RecordError as exc:
        sys.stderr.write(f"baseline_compare record: {exc}\n")
        return 2
    return 0


def _main_render(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(prog="baseline_compare.py render")
    ap.add_argument("--published", type=Path, required=True)
    ap.add_argument("--published-source", required=True)
    ap.add_argument("--old", type=Path, required=True)
    ap.add_argument("--corrected", type=Path, required=True)
    ap.add_argument("--doc", type=Path, required=True)
    args = ap.parse_args(argv)
    published_text = args.published.read_text(encoding="utf-8")
    old = json.loads(args.old.read_text(encoding="utf-8"))
    corrected = json.loads(args.corrected.read_text(encoding="utf-8"))
    try:
        block = render_comparison(published_text, args.published_source, old, corrected)
        doc_text = args.doc.read_text(encoding="utf-8")
        new_doc = splice_generated(doc_text, block)
    except ValueError as exc:
        sys.stderr.write(f"baseline_compare render: {exc}\n")
        return 2
    args.doc.write_text(new_doc, encoding="utf-8")
    return 0


def main(argv: list[str] | None = None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    if not argv:
        sys.stderr.write("baseline_compare: missing subcommand (record|render)\n")
        return 2
    sub, rest = argv[0], argv[1:]
    if sub == "record":
        return _main_record(rest)
    if sub == "render":
        return _main_render(rest)
    sys.stderr.write(f"baseline_compare: unknown subcommand {sub!r}\n")
    return 2


if __name__ == "__main__":
    sys.exit(main())
