#!/usr/bin/env python3
"""jira_artifacts.py — build GitLab blob links for klc artefacts.

Does NOT upload files. Only builds a comment-ready link table from
artefacts that actually exist on disk.

Exports:
    ARTIFACT_LINK_MARKER  — HTML comment marker for idempotency
    build_artifact_links(ticket, cfg) -> str   — markdown link table
    upsert_artifact_links(client, key, ticket, cfg) -> None  — add or update
"""
from __future__ import annotations

import sys
from pathlib import Path

_file_dir = Path(__file__).resolve().parent
_project_root = _file_dir.parent.parent
sys.path.insert(0, str(_project_root))
from core.shared.paths import klc_ticket_dir  # noqa: E402

ARTIFACT_LINK_MARKER = "<!-- klc:artifact-links {key} -->"
ARTIFACT_LINK_MARKER_END = "<!-- /klc:artifact-links -->"


def build_artifact_links(ticket: str, cfg: "JiraConfig") -> str:  # type: ignore[name-defined]
    """Return a markdown comment body with GitLab links for existing artefacts.

    Only artefacts that exist on disk are included. Missing files are silently
    omitted. Returns an empty string (with just markers) if nothing exists.
    """
    from jira_config import JiraConfig  # noqa: F401 (type check only)

    ticket_dir = klc_ticket_dir(ticket)
    lines = []
    ticket_dir_resolved = ticket_dir.resolve()
    for name, rel_path in (cfg.artifact_paths or {}).items():
        full_path = ticket_dir / rel_path
        # Reject absolute paths and traversals outside ticket directory.
        try:
            resolved = full_path.resolve()
            if not str(resolved).startswith(str(ticket_dir_resolved)):
                continue
        except Exception:
            continue
        if full_path.exists():
            # ticket_dir relative to project root for the URL
            try:
                proj_root = ticket_dir.parent.parent.parent  # tickets/<key> → .klc → project
                url_path = full_path.relative_to(proj_root).as_posix()
            except ValueError:
                url_path = rel_path
            url = cfg.artifact_link_url(url_path)
            label = name.replace("_", " ").title()
            lines.append(f"- [{label}]({url})")

    marker_start = ARTIFACT_LINK_MARKER.format(key=ticket)
    body_lines = [
        marker_start,
        f"**KLC artefacts for {ticket}** (auto-generated by klc)",
        "_moved by klc_",
        "",
    ]
    if lines:
        body_lines.extend(lines)
    else:
        body_lines.append("_(no artefacts yet)_")
    body_lines.append(ARTIFACT_LINK_MARKER_END)
    return "\n".join(body_lines)


class _CommentReadError(Exception):
    """Raised when comment list retrieval fails; prevents spurious add_comment."""


def _find_link_comment(client: "JiraClient",  # type: ignore[name-defined]
                        key: str) -> tuple[str | None, str | None]:
    """Return (comment_id, body) for the existing artefact-link comment, or (None, None).

    Raises _CommentReadError on retrieval failure so callers skip the write
    and avoid duplicating marker comments after transient errors.
    """
    marker = ARTIFACT_LINK_MARKER.format(key=key)
    try:
        comments = client.get_issue_comments(key)
    except RuntimeError as exc:
        raise _CommentReadError(str(exc)) from exc
    for comment in comments:
        body = comment.get("body", "")
        # REST API v3 returns ADF body; plain-text body in v2 and FakeClient
        if isinstance(body, str) and marker in body:
            return comment["id"], body
        # Handle ADF body (nested structure)
        if isinstance(body, dict):
            # Flatten ADF to text for marker detection
            flat = _flatten_adf(body)
            if marker in flat:
                return comment["id"], flat
    return None, None


def flatten_adf(adf: dict) -> str:
    """Recursively extract text from Atlassian Document Format (ADF).

    Exported so intake.py can reuse without duplication.
    """
    parts = []
    if adf.get("type") == "text":
        parts.append(adf.get("text", ""))
    for child in adf.get("content") or []:
        parts.append(flatten_adf(child))
    return "".join(parts)


# Keep internal alias for backward compat within this module
_flatten_adf = flatten_adf


def upsert_artifact_links(client: "JiraClient",  # type: ignore[name-defined]
                           key: str,
                           ticket: str,
                           cfg: "JiraConfig") -> None:  # type: ignore[name-defined]
    """Add or update the artefact-link comment in the Jira issue.

    Idempotent: finds the existing marker comment and updates it; creates
    a new one only if no marker comment exists.
    """
    if not cfg.comment_links:
        return

    body = build_artifact_links(ticket, cfg)
    try:
        comment_id, _ = _find_link_comment(client, key)
    except _CommentReadError as exc:
        # Cannot determine if marker comment already exists — skip write to
        # prevent duplicate comments. Caller receives a non-fatal warning.
        import sys as _sys
        _sys.stderr.write(
            f"[jira] artefact link upsert skipped for {key}: "
            f"could not list comments ({exc})\n"
        )
        return

    if comment_id is not None:
        client.update_comment(key, comment_id, body)
    else:
        client.add_comment(key, body)
